### ISSUE TITLE
Give errors and dont run!

### ISSUE THREAD

**Issue by merecesarchviz** [hallatore/stable-diffusion-webui-chatgpt-utilities#1]
Hi,

I installed it in my stable diffusion and set the api key in the settings but whe i try to generate something give me all this errors!

Chat GPT request:
I want you to act as a prompt generator. Compose each answer as a visual sentence. Do not write explanations on replies. Format the answers as javascript json arrays with a single string per answer. Return exactly 4 to my question. Answer the questions exactly. Answer the following question:
Describe an epic d&d scene using the prompt ""a warlock man with a hero look"" as inspiration. Describe the person, clothing/armor and atmosphere. Don´t use any name or artist names from the original prompt. Give me 8 examples with unique characteristics. Return only a short description.

Error completing request
Arguments: ('task(w7qqill1xjysrzo)', 'a warlock man with a hero look', '', [], 20, 15, False, False, 1, 1, 4.5, -1.0, -1.0, 0, 0, 0, False, 512, 512, False, 0.7, 2, 'Latent', 0, 0, 0, [], 6, False, True, False, 0, -1, False, '', False, False, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'Refresh models', False, True, False, 'none', 'None', 1, None, False, 'Scale to Fit (Inner Fit)', False, False, 64, 64, 64, 0, 1, False, False, 'none', 'None', 1, None, False, 'Scale to Fit (Inner Fit)', False, False, 64, 64, 64, 0, 1, False, False, False, False, False, '1:1,1:2,1:2', '0:0,0:0,0:1', '0.2,0.8,0.8', 20, False, False, 'positive', 'comma', 0, False, False, '', 1, '', 0, '', 0, '', True, False, False, False, 0, None, None, 50, 'Describe an epic d&d scene using the prompt "{prompt}" as inspiration.\nDescribe the person, clothing/armor and atmosphere.\nDon´t use any name or artist names from the original prompt.\nGive me 8 examples with unique characteristics.\nReturn only a short description.', 4.0, False, '', '', False, False, False, 0, 0, 512, 512, False, False, True, True, True, False, False, 1, False, False, 2.5, 4, 0, False, 0, 1, False, False, 'u2net', False, False, False, False) {}
Traceback (most recent call last):
  File "F:\SD\stable-diffusion-webui\extensions\stable-diffusion-webui-chatgpt-utilities\scripts\chatgpt_utils.py", line 10, in retry_query_chatgpt
    chatgpt_answers = query_chatgpt(messages, count)
  File "F:\SD\stable-diffusion-webui\extensions\stable-diffusion-webui-chatgpt-utilities\scripts\chatgpt_utils.py", line 26, in query_chatgpt
    chat_gpt_response = get_chat_completion([
  File "F:\SD\stable-diffusion-webui\extensions\stable-diffusion-webui-chatgpt-utilities\scripts\chatgpt_utils.py", line 52, in get_chat_completion
    completion = openai.ChatCompletion.create(model="gpt-3.5-turbo", messages=messages, temperature=0.5)
  File "F:\SD\stable-diffusion-webui\venv\lib\site-packages\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "F:\SD\stable-diffusion-webui\venv\lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "F:\SD\stable-diffusion-webui\venv\lib\site-packages\openai\api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "F:\SD\stable-diffusion-webui\venv\lib\site-packages\openai\api_requestor.py", line 619, in _interpret_response
    self._interpret_response_line(
  File "F:\SD\stable-diffusion-webui\venv\lib\site-packages\openai\api_requestor.py", line 679, in _interpret_response_line
    raise self.handle_error_response(
openai.error.RateLimitError: You exceeded your current quota, please check your plan and billing details.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\SD\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "F:\SD\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "F:\SD\stable-diffusion-webui\modules\txt2img.py", line 53, in txt2img
    processed = modules.scripts.scripts_txt2img.run(p, *args)
  File "F:\SD\stable-diffusion-webui\modules\scripts.py", line 376, in run
    processed = script.run(p, *script_args)
  File "F:\SD\stable-diffusion-webui\extensions\stable-diffusion-webui-chatgpt-utilities\scripts\prompt_chatgpt.py", line 110, in run
    chatgpt_answers = retry_query_chatgpt(chatgpt_prompt, int(chatgpt_batch_count), 3)
  File "F:\SD\stable-diffusion-webui\extensions\stable-diffusion-webui-chatgpt-utilities\scripts\chatgpt_utils.py", line 12, in retry_query_chatgpt
    if (len(chatgpt_answers) == count):
UnboundLocalError: local variable 'chatgpt_answers' referenced before assignment

**Comment by hallatore** [comment]
Can you try the latest version? Pushed a small change.

**Comment by merecesarchviz** [comment]
I installed it and close the SD and open again but still the same a lot of errors!

Chat GPT request:
I want you to act as a prompt generator. Compose each answer as a visual sentence. Do not write explanations on replies. Format the answers as javascript json arrays with a single string per answer. Return exactly 4 to my question. Answer the questions exactly. Answer the following question:
Take the prompt "a women with a red color hair" and change the word [COLOR] with a random color description.

ChatGPT query failed. Retrying. Error: You exceeded your current quota, please check your plan and billing details.
Chat GPT request:
I want you to act as a prompt generator. Compose each answer as a visual sentence. Do not write explanations on replies. Format the answers as javascript json arrays with a single string per answer. Return exactly 4 to my question. Answer the questions exactly. Answer the following question:
Take the prompt "a women with a red color hair" and change the word [COLOR] with a random color description.

ChatGPT query failed. Retrying. Error: You exceeded your current quota, please check your plan and billing details.
Chat GPT request:
I want you to act as a prompt generator. Compose each answer as a visual sentence. Do not write explanations on replies. Format the answers as javascript json arrays with a single string per answer. Return exactly 4 to my question. Answer the questions exactly. Answer the following question:
Take the prompt "a women with a red color hair" and change the word [COLOR] with a random color description.

Error completing request
Arguments: ('task(s9fejozshuccdrz)', 'a women with a red color hair', '', [], 20, 0, False, False, 1, 1, 7, -1.0, -1.0, 0, 0, 0, False, 512, 512, False, 0.7, 2, 'Latent', 0, 0, 0, [], 6, False, True, False, 0, -1, False, '', False, False, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'Refresh models', False, True, False, 'none', 'None', 1, None, False, 'Scale to Fit (Inner Fit)', False, False, 64, 64, 64, 0, 1, False, False, 'none', 'None', 1, None, False, 'Scale to Fit (Inner Fit)', False, False, 64, 64, 64, 0, 1, False, False, False, False, False, '1:1,1:2,1:2', '0:0,0:0,0:1', '0.2,0.8,0.8', 20, False, False, 'positive', 'comma', 0, False, False, '', 1, '', 0, '', 0, '', True, False, False, False, 0, None, None, 50, 'Take the prompt {prompt} and change the word [COLOR] with a random color description.', 4.0, False, '', '', False, False, False, 0, 0, 512, 512, False, False, True, True, True, False, False, 1, False, False, 2.5, 4, 0, False, 0, 1, False, False, 'u2net', False, False, False, False) {}
Traceback (most recent call last):
  File "F:\SD\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "F:\SD\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "F:\SD\stable-diffusion-webui\modules\txt2img.py", line 53, in txt2img
    processed = modules.scripts.scripts_txt2img.run(p, *args)
  File "F:\SD\stable-diffusion-webui\modules\scripts.py", line 376, in run
    processed = script.run(p, *script_args)
  File "F:\SD\stable-diffusion-webui\extensions\stable-diffusion-webui-chatgpt-utilities\scripts\prompt_chatgpt.py", line 110, in run
    chatgpt_answers = retry_query_chatgpt(chatgpt_prompt, int(chatgpt_batch_count), 3)
  File "F:\SD\stable-diffusion-webui\extensions\stable-diffusion-webui-chatgpt-utilities\scripts\chatgpt_utils.py", line 18, in retry_query_chatgpt
    raise e
  File "F:\SD\stable-diffusion-webui\extensions\stable-diffusion-webui-chatgpt-utilities\scripts\chatgpt_utils.py", line 12, in retry_query_chatgpt
    chatgpt_answers = query_chatgpt(messages, count)
  File "F:\SD\stable-diffusion-webui\extensions\stable-diffusion-webui-chatgpt-utilities\scripts\chatgpt_utils.py", line 33, in query_chatgpt
    chat_gpt_response = get_chat_completion([
  File "F:\SD\stable-diffusion-webui\extensions\stable-diffusion-webui-chatgpt-utilities\scripts\chatgpt_utils.py", line 59, in get_chat_completion
    completion = openai.ChatCompletion.create(model="gpt-3.5-turbo", messages=messages, temperature=0.5)
  File "F:\SD\stable-diffusion-webui\venv\lib\site-packages\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "F:\SD\stable-diffusion-webui\venv\lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "F:\SD\stable-diffusion-webui\venv\lib\site-packages\openai\api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "F:\SD\stable-diffusion-webui\venv\lib\site-packages\openai\api_requestor.py", line 619, in _interpret_response
    self._interpret_response_line(
  File "F:\SD\stable-diffusion-webui\venv\lib\site-packages\openai\api_requestor.py", line 679, in _interpret_response_line
    raise self.handle_error_response(
openai.error.RateLimitError: You exceeded your current quota, please check your plan and billing details.

**Comment by merecesarchviz** [comment]
In the website i still can generate it! is strange

**Comment by hallatore** [comment]
The website is free, or you have ChatGPT Plus.
But you need an openai budget to use the api directly.

It's practically free though. I've spent $1 so far in total the last week.
