### ISSUE TITLE
This error always happens

### ISSUE THREAD

**Issue by rtyeye** [hallatore/stable-diffusion-webui-chatgpt-utilities#3]
hello
good extensions, i'm glad to use this
but i can use it just only one time after i install this

and always after restart the colab, this happens

Error loading script: chatgpt_utils.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/stable-diffusion-webui-chatgpt-utilities/scripts/chatgpt_utils.py", line 3, in <module>
    import openai
ModuleNotFoundError: No module named 'openai'

Error loading script: json_utils.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/stable-diffusion-webui-chatgpt-utilities/scripts/json_utils.py", line 2, in <module>
    import json5
ModuleNotFoundError: No module named 'json5'

Error loading script: prompt_chatgpt.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/stable-diffusion-webui-chatgpt-utilities/scripts/prompt_chatgpt.py", line 3, in <module>
    import openai
ModuleNotFoundError: No module named 'openai'

what is the problem? im not major in computer and i dont know python so i cannot handle it.. please help

**Comment by hallatore** [comment]
Can you try the latest code and see if it works?
I tweaked how requirements are installed.

**Comment by rtyeye** [comment]
I did it and it works very well
thank you veryvery much for your help....
It's so amazing extensions i ever used!!

2023년 3월 11일 (토) 오후 5:11, Tore Lervik ***@***.***>님이 작성:
