### ISSUE TITLE
Sorry for asking again

### ISSUE THREAD

**Issue by rtyeye** [hallatore/stable-diffusion-webui-chatgpt-utilities#4]
After you answer with my question,

Error loading script: chatgpt_utils.py
Traceback (most recent call last):
File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 229, in load_scripts
script_module = script_loading.load_module(scriptfile.path)
File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
module_spec.loader.exec_module(module)
File "", line 850, in exec_module
File "", line 228, in _call_with_frames_removed
File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/stable-diffusion-webui-chatgpt-utilities/scripts/chatgpt_utils.py", line 3, in
import openai
ModuleNotFoundError: No module named 'openai'

Error loading script: json_utils.py
Traceback (most recent call last):
File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 229, in load_scripts
script_module = script_loading.load_module(scriptfile.path)
File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
module_spec.loader.exec_module(module)
File "", line 850, in exec_module
File "", line 228, in _call_with_frames_removed
File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/stable-diffusion-webui-chatgpt-utilities/scripts/json_utils.py", line 2, in
import json5
ModuleNotFoundError: No module named 'json5'

Error loading script: prompt_chatgpt.py
Traceback (most recent call last):
File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 229, in load_scripts
script_module = script_loading.load_module(scriptfile.path)
File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
module_spec.loader.exec_module(module)
File "", line 850, in exec_module
File "", line 228, in _call_with_frames_removed
File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/stable-diffusion-webui-chatgpt-utilities/scripts/prompt_chatgpt.py", line 3, in
import openai
ModuleNotFoundError: No module named 'openai'

this error happened again after 1day i restart the colab
so i install json5 and openai by using the code

pip uninstall openai
pip install --upgrade pip
pip install openai
pip install json5

but the error 

Error loading script: prompt_chatgpt.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 248, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "frozen importlib._bootstrap_external>", line 846, in exec_module
  File "frozen importlib._bootstrap_external>", line 983, in get_code
  File "frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/stable-diffusion-webui-chatgpt-utilities/scripts/prompt_chatgpt.py", line 123
    match precision_dropdown:
          ^
SyntaxError: invalid syntax

I erased <

this happened...
i tried to solve it myself.. but it's out of my control, i think
i'm completely blind at python and computer science.. so sorry for asking you to help me again
can you help me?

**Comment by hallatore** [comment]
No problem!
I see that match is a python 3.10 feature. I replaced it with normal if/else.
It should work now :)

Not sure about the installs and colab. I guess it happens because you get a new VM it runs on. I host it on my own pc, so I never have to reinstall stuff.

**Comment by rtyeye** [comment]
Thank you for your great help again :)
It works well !!!!!
